---
name: Task Template
about: Use this template for child tasks
title: ''
labels: task
assignees: ''

---

# **Description**
**Task**:  One line description of task
**Feature**: Parent feature description and link (#0)

In depth description here

# **Dependencies**
-  Dependency! (#0)

# **Milestones**
- [ ] Milestone!

# **Members**
- Treffery (@tweeeb )
